### ISSUE TITLE
"May 2022" platform security guide had a December update

### ISSUE THREAD

**Issue by Siguza** [0xmachos/Apple-Platform-Security-Guides#1]
Sup.

The [latest revision of Apple's Platform Security Guide](https://help.apple.com/pdf/security/en_US/apple-platform-security-guide.pdf) shows a revision in December 2022 (which you don't seem to have in your repo), though the date in the cover page still says May 2022.  
Don't know how you wanna handle that, but though I'd alert you to that fact.

**Comment by 0xmachos** [comment]
Sorry I missed this, cheers for letting me know. Do you have a copy of that document we can add?

**Comment by Siguza** [comment]
Sure.

[Apple_Platform_Security_Guide-2022-12.pdf](https://github.com/0xmachos/Apple-Platform-Security-Guides/files/15334581/Apple_Platform_Security_Guide-2022-12.pdf)

**Comment by 0xmachos** [comment]
Added the above linked [`Apple_Platform_Security_Guide-2022-12.pdf`](https://github.com/0xmachos/Apple-Platform-Security-Guides/files/15334581/Apple_Platform_Security_Guide-2022-12.pdf) in: 
* bee6ea8a0d86544a5c51a2dbb8b5092a1bf9f788
* d75646fe9572ae6a6d61b7598698a70adce17e1a
* 7a443d3027f40af9314a2496c525f1aa1d82552e

@Siguza thanks for letting me know about this, really appreciate it.
